server:
  port: 1111
eureka:
  instance:
    hostname: 172.16.52.78
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://172.16.52.78:1111/eureka/
